# Generated by Django
from django.db import migrations


def populate_jti_hex(apps, schema_editor):
    OutstandingToken = apps.get_model("token_blacklist", "OutstandingToken")
    for token in OutstandingToken.objects.all():
        token.jti_hex = token.jti.hex
        token.save(update_fields=["jti_hex"])


def reverse_populate_jti_hex(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0002_outstandingtoken_jti_hex'),
    ]

    operations = [
        migrations.RunPython(populate_jti_hex, reverse_populate_jti_hex),
    ]
