# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0003_auto_20171017_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstandingtoken',
            name='jti',
        ),
    ]
