# Generated by Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0004_auto_20171017_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outstandingtoken',
            old_name='jti_hex',
            new_name='jti',
        ),
    ]
