# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0005_auto_20171017_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outstandingtoken',
            name='jti',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
