# Generated by Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0006_auto_20171017_2113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outstandingtoken',
            options={'ordering': ('user',)},
        ),
    ]
